[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cade_economy = "CbMfmQta38TTXDqKYQRZ73nV6JY2nGU5QyoVpx3mXW3J"

[registry]
url = "https://frosty-smart-smoke.solana-devnet.quiknode.pro/011aa36eee4c55c5bd8b2290980d614e2fc2c171/"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
